export const ITEM_CATEGORIES = [
    "Photography",
    "Electronics",
    "Furniture",
    "Sports",
    "Music",
    "Gaming",
    "Vehicles",
    "Camping Gear",
    "Party Supplies",
    "Appliances",
    "Tools",
    "Home Improvement",
    "Garden & Outdoor",
    "Audio & Sound",
    "Projectors & Screens",
    "Computers & Laptops",
    "Mobile & Tablets",
    "Fitness Equipment",
    "Baby & Kids",
    "Books & Study",
    "Fashion & Costumes",
    "Medical Equipment",
    "Travel Gear",
    "Event Equipment",
    "Other"
];
